/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class silence_devices_midas_MidasDevice */

#ifndef _Included_silence_devices_midas_MidasDevice
#define _Included_silence_devices_midas_MidasDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     silence_devices_midas_MidasDevice
 * Method:    synced
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_silence_devices_midas_MidasDevice_synced
  (JNIEnv *, jobject);

/*
 * Class:     silence_devices_midas_MidasDevice
 * Method:    init
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_silence_devices_midas_MidasDevice_init
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     silence_devices_midas_MidasDevice
 * Method:    setVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_silence_devices_midas_MidasDevice_setVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     silence_devices_midas_MidasDevice
 * Method:    Nplay
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_silence_devices_midas_MidasDevice_Nplay
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     silence_devices_midas_MidasDevice
 * Method:    Nstop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_silence_devices_midas_MidasDevice_Nstop
  (JNIEnv *, jobject);

/*
 * Class:     silence_devices_midas_MidasDevice
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_silence_devices_midas_MidasDevice_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
