/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class silence_devices_fmod_FmodDevice */

#ifndef _Included_silence_devices_fmod_FmodDevice
#define _Included_silence_devices_fmod_FmodDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     silence_devices_fmod_FmodDevice
 * Method:    Nplay
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_silence_devices_fmod_FmodDevice_Nplay
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     silence_devices_fmod_FmodDevice
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_silence_devices_fmod_FmodDevice_pause
  (JNIEnv *, jobject);
/*
 * Class:     silence_devices_fmod_FmodDevice
 * Method:    Nstop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_silence_devices_fmod_FmodDevice_Nstop
  (JNIEnv *, jobject);

/*
 * Class:     silence_devices_fmod_FmodDevice
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_silence_devices_fmod_FmodDevice_close
  (JNIEnv *, jobject);

/*
 * Class:     silence_devices_fmod_FmodDevice
 * Method:    init
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_silence_devices_fmod_FmodDevice_init
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     silence_devices_fmod_FmodDevice
 * Method:    setVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_silence_devices_fmod_FmodDevice_setVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     silence_devices_fmod_FmodDevice
 * Method:    synced
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_silence_devices_fmod_FmodDevice_synced
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
